<?php
/**
 * @file order_example.install
 */

/**
 * Implements hook_enable().
 *
 * Here we'll just use the commerce_order function to define a non-default
 * order type. If we wanted different default fields on it, we could copy
 * and alter commerce_order_configure_order_type().
 *
 * This order type (bundle) is not exposed on the current commerce admin pages
 * however.
 */
function order_example_enable() {
  commerce_order_configure_order_type('order_example_order_type');
}
